### ISSUE TITLE
ExceptionLogger model no longer serialize some attributes

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#102]
The ExceptionLogger model is used to give admins and developers access to internally raised exceptions. It's a standard ActiveRecord model with 4 attributes being serialized (see excetpion_logger.rb).

It seems that since the latest upgrades, some of the serialized attributes are no longer de-serialized when reloading the objects. In production I have found some record where the attributes :request and/or :session come back as plain strings. This breaks the view code, because the 'show' page of ExceptionLogger tries to do things like `@exception.session.keys` and session() returns a string instead of a hash.

The session attribute (containing a session object) seems to be serialized properly, at least the content seems to be valid YAML code, but it's never rebuilt when find() is invoked, it stays a string.

**Comment by remibernard** [comment]
This issue occurs because `session` is not a plain hash, its a [`Rack::Session::Abstract::SessionHash`](https://github.com/rack/rack/blob/rack-1.4/lib/rack/session/abstract/id.rb#L50), a subclass of `Hash` which requires 2 arguments to construct. [Psych's YAML module](https://github.com/tenderlove/psych/blob/master/lib/psych/visitors/to_ruby.rb#L279) tries to create that object without supplying any arguments to the constructor, causing an `ArgumentError`. This error is then explicitly caught by Rails' [`YAMLColumn`](https://github.com/rails/rails/blob/3-2-stable/activerecord/lib/active_record/coders/yaml_column.rb#L21), which finally returns the original string.

The solution is very simple; convert `Rack::Session::Abstract::SessionHash` to a regular hash. (`to_hash` method)
