### ISSUE TITLE
update to survey link in the NeuroHub Portal to reference Beta questionnaire

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#1022]
On the NeuroHub portal dashboard page there is on the bottom left a link to the user survey form.  That link is presently pointing to the NeuroHub Alpha User Testing Survey.

See the attached image.

The survey has been updated slightly to reflect the Beta testing environment.  As such the link on the page needs to be updated, since a reminder will be today going out to users asking them to provide their feedback.

Please update the survey link to point to the NEW location.

Old Survey Link:
https://docs.google.com/forms/d/e/1FAIpQLSepzm7l-OwvU_XN-b8ZRZF5aDJgi3QXGq_AqM0Zj9x-Asiw4w/viewform
New Survey Link:
https://docs.google.com/forms/d/e/1FAIpQLSfQnYwSUgzj6VMXEUMFEpsFZC0A9lwJVSc-Vbvpy3drjmebkQ/viewform

On https://portal.neurohub.ca/neurohub:
![Screen Shot 2020-09-23 at 1 43 54 PM](https://user-images.githubusercontent.com/65622686/94049351-e236e880-fda2-11ea-9e63-223178201dd3.png)

**Comment by bryancaron** [comment]
Also, please change the wording so that it says in the Survey section "Dear Users" instead of "Dear testers".  Thanks.

**Comment by prioux** [comment]
At some point we need to make this section editable/configurable by the admin, not hardcoded in the page's code. The reason it's hardcoded right now is simply because during development we simply didn't have time to add configurable elements in the site.

Right now it also means that any person in the entire world can go to that google doc survey, just by finding the URL in the cbrain code base here on GitHub. They don't even have to be NeuroHub users.

**Comment by bryancaron** [comment]
Another element to edit, under the New Portal under construction block:

Change "NeuroHub is leveraging existing technologies" to "NeuroHub is building upon and continuing advance technologies".

**Comment by prioux** [comment]
Fixed by #1024
