### ISSUE TITLE
 Message model clunky.

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#129]
It works fine on its own, but I realized in some recent work that's it's really not easy to subclass. I had to put some knowledge about the subclass in the method Message.sent_message to get it to work properly. It would be nice if this were done a little more cleanly.

Redmine: 3289

**Comment by remibernard** [comment]
Doesn't seem valid anymore. AFAIK, there is no subclass knowledge in Message right now, and the one mentioned by Tarek in this issue seems to be related to commit f02086c7eca, ([message.rb:161](https://github.com/aces/cbrain/commit/f02086c7eca#diff-9319b93675f76326624812eab922355dR161)), which doesn't strike me as subclass-dependent.
