### ISSUE TITLE
A new invalid Data Provider may break the Data Provider  list page

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain#1402]
Steps to reproduce

1. Create a new smart Data Provider (e.g. Carmin), but do not fill Physical Data Location
aka Full Directory Path. Actually, do not fill any fields but name, that should be enough

2. Go to the Data Provider list.

Expected : you still can see the list of data providers

Observed: 500 error

**Comment by prioux** [comment]
Is this only with Carmin DPs or does this happen with other types?

**Comment by prioux** [comment]
We're going to junk all CARMIN stuff out of CBRAIN anyway, soon.

**Comment by MontrealSergiy** [comment]
No any smart

**Comment by prioux** [comment]
Well, then, identify which attributes are not set that cause the index page to fail and then

1) if a DP requires that attribute anyway, make sure the ActiveRecord validation rules ensures it cannot be saved without it
2) if a DP shoudl work without that attribute, then make sure the index page doesn't crash because of it's missing.

**Comment by prioux** [comment]
Make sure to list here which attributes are faulty, please; don't make a pull request righr away, I'd like to review them first.

**Comment by MontrealSergiy** [comment]
`@real_provider`

**Comment by prioux** [comment]
Do you meant `remote_dir` ? I can't find `remote_path` anywhere. And I don't see where in the DP index page the exception is raised.

**Comment by prioux** [comment]
Fixed in my most recent commit: https://github.com/aces/cbrain/commit/1702bfa01476ec0f1d1f8fa74317dd30bad32377
