### ISSUE TITLE
Bug in scope filtering

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#249]
When viewing the Bourreau index page, if there are active tasks on the bourreau a link with the number of task is shown; that link is supposed to take us to the task index page with two filters applied: one for the bourrreau ID and one for the status 'active'. An exception is generated however:

```
Internal error: Exception Caught; Exception: Psych::DisallowedClass 
Exception: Psych::DisallowedClass: Tried to load unspecified class: Symbol
```

The params requests, when clicking on the link, looks like this:

```ruby
{"_scope_mode"=>"replace", "_scopes"=>{"tasks"=>"H4sIAFMsOVYAA9PV1eVKs-LSVUi0UkjKLy0qSk0sjc9M4VJQKLNSMIKIF5cklpQWQ4SsEpNLMstSuQCVhq5COAAAAA"}}
```
Decoding the filter I find:

```bash
echo -n 'H4sIAFMsOVYAA9PV1eVKs+LSVUi0UkjKLy0qSk0sjc9M4VJQKLNSMIKIF5cklpQWQ4SsEpNLMstSuQCVhq5COAAAAAAA' | base64 -d  | gunzip -c
```

which yields:

```
---
f:
- a: bourreau_id
  v: 2
- a: status
  v: :active
```

The problem seems related to the ':active' symbol.

**Comment by remibernard** [comment]
Adding `value = value.to_s if value.is_a?(Symbol)` before [scope_helper.rb:774](https://github.com/aces/cbrain/blob/master/BrainPortal/app/helpers/scope_helper.rb#L774) should fix this. I'm not a fan of special-casing classes like this, but `Symbol` is the odd one out in YAML serialization due to security issues before Ruby 2.2.

I'll test & push this fix to `dev` ASAP.
