### ISSUE TITLE
Wrong pagination page number makes file list disappear

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#276]
In some situation, if the user is at page N of an index, and the user changes the filters
so that the results fit in less than N pages, then no data is shown in the index. It's particularly
annoying when you change to a list which fits in a single page, what is shown is an ampty
table with no way to switch back to page 1.

**Comment by remibernard** [comment]
I can't seem to reproduce this one right now. Which exact operations trigger the bug?

**Comment by prioux** [comment]
The problem is: I'm not sure. It happened to some of our users at Douglas....

**Comment by remibernard** [comment]
Steps to reproduce:

1. Have a scope filter applied returning a multi-page result.
2. Switch to any page but the first.
3. Apply a custom filter which should return less than a single page worth of results.
4. The returned result set will be empty.

**Comment by remibernard** [comment]
It turns out there is two ways this bug can be fixed:

- I can add an explicit count operation to `Scope::Pagination`'s `apply` method ([view_scopes.rb:983](https://github.com/aces/cbrain/blob/cbf3e742c33c20efbe356f61d6ca3bc79932274d/BrainPortal/lib/view_scopes.rb#L983)) and cap `@page` to the corresponding value. While cleaner, this solution will force a SQL `COUNT(*)` query for AR models and is thus slower.

- I can force the page number to 1 when applying a custom filter manually in [_filters.html.erb](https://github.com/aces/cbrain/blob/cbf3e742c33c20efbe356f61d6ca3bc79932274d/BrainPortal/app/views/userfiles/_filters.html.erb#L38), just like what is employed to avoid this bug when using the dynamic table filters ([dynamic_table_helper.rb:1034](https://github.com/aces/cbrain/blob/cbf3e742c33c20efbe356f61d6ca3bc79932274d/BrainPortal/app/helpers/dynamic_table_helper.rb#L1034)). While faster and somewhat simpler to implement, this solution is somewhat hacky (its not really the view's job to reset the page number) and needs to be added manually wherever  a scope link is made.

I would personally go for the first approach, but I am unsure of the performance impact.

**Comment by prioux** [comment]
Go with the AR.count() .

**Comment by remibernard** [comment]
This should be closed, as commit e22dfc3d9950f933fc93c2baef5d1894ddca65b8 fixes this and was merged into `dev` by pull request #279.

**Comment by prioux** [comment]
Remi says it's closed.
