### ISSUE TITLE
Load info no longer shown in Bourreau index page tooltip

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#335]
There used to be load information shown in a tooltip that appeared when you hovered over the numbers in the 'tasks' column of the Bourreau index page. Now the tooltip appears but the numbers are always missing. See screenshot.

![screen shot 2016-02-18 at 15 18 26](https://cloud.githubusercontent.com/assets/777588/13156943/1f4b87de-d653-11e5-8934-e36444b1bb24.png)

**Comment by remibernard** [comment]
As weird as it may seem, this is a very old bug. It appears to have been introduced with commit 9eefffdf10327db0ab6da6a425b786303772d246, which makes the `load_info` partial generating the tooltip rely on instance variables (`@num_active`, `@num_queued` and `@num_processing`) supplied by the corresponding [`load_info`](https://github.com/aces/cbrain/blob/9eefffdf10327db0ab6da6a425b786303772d246/BrainPortal/app/controllers/bourreaux_controller.rb#L210) controller action. As `load_info` is not invoked when the index page is generated, the corresponding instance variables are empty and so is the tooltip.

Since I'm a bit overwhelmed with work these days, I'll have to pass this on to @natacha-beck, the author of commit 9eefffdf10327db0ab6da6a425b786303772d246.

**Comment by prioux** [comment]
No prob, I suspected as much. Don't worry about issues assigned to you, in general, it's more important for you to work on the rest. And I appreciate your hints and comments, every time.
