### ISSUE TITLE
Upload limit on dev?

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#337]
In app/view/userfiles/_dialogs.html.erb, we have a nice TODO...:
 
`data-max-upload-size="" <%# TODO %>`

I found no upload limit elsewhere for the upload-size, am I right ? So in the Dev branch the user can upload files of any size ?

**Comment by remibernard** [comment]
AFAIK, the limit is actually enforced by nginx, not CBRAIN per se. As such this limit is mainly there as a nice indication to the user. At the time I made the new interface, there was no clear place (or value) for this limit, hence the `TODO`.

Maybe it could be placed in CBRAIN's config? Or fetched from nginx in some way?

**Comment by prioux** [comment]
Well, certainly not fetched from nginx, because I can well imagine CBRAIN installation without nginx. E.g. the rails apps on our dev workstations.
We still need a nice place to record a limit, and show it to the user, and then we can inforce it the best we can within CBRAIN while allowing sysadmins who deploy it to have it enforced externally (e.g. with nginx) too.
