### ISSUE TITLE
Handling of flags in Boutiques.

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#373]
Boutiques implementation in CBRAIN has the following bug with the handling of flags: for it will substitute "-a false" on the command line when flag "-a" is not active.

This bug fix is required for all the Boutiques tool that have inputs of type Flag:
* https://github.com/glatard/cbrain-plugins-psom/issues/5
* MINCBet

**Comment by prioux** [comment]
Just to help, I think the bug is in

    BrainPortal/lib/cbrain_task_generators/templates/bourreau.rb.erb

in method **apply_template()**

**Comment by glatard** [comment]
btw, @ttaa9, you can write in files the Ruby classes generated by Boutiques using the following command in the Rails console:
`(SchemaTaskGenerator.generate "./lib/cbrain_task_generators/schemas/boutiques.schema.json","cbrain_plugins/.../<tool>.json").to_directory("<some_path>")`

**Comment by remibernard** [comment]
[bourreau.rb.erb:438](https://github.com/aces/cbrain/blame/master/BrainPortal/lib/cbrain_task_generators/templates/bourreau.rb.erb#L438)
```ruby
next template.gsub(key, flag) if flag && value == true
```

An explicit is-bool check instead of `value == true` and a ternary for the substitution value should do it.

As for being opaque, not sure how I could've made it clearer without making it a lot longer. Each block should be pretty straightforward to understand...

**Comment by glatard** [comment]
The code is not opaque, it's clear and well documented. Thanks for the hint @remibernard!

**Comment by ttaa9** [comment]
I've done as @remibernard recommended and it seems to have worked. Thanks!
