### ISSUE TITLE
Don't start portal if auth_token is nil

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#48]
A portal may have a nil auth_token when, for some reason, its cache dir does not contain a file pair (DP_Cache_Key.md5,DP_Cache_Rev.id). In this case all the communications with the Bourreau fail because the portal has no sender id. It would save debugging time if the portal checked its auth_token at startup, and refused to start if it's nil.

Original Author: Tristan

Pierre: 
Hum... this is all supposed to be taken care of by the boot process... I'll check.
Is there any mechanism to reproduce?

**Comment by remibernard** [comment]
Commit 201219a63c2a264486c16c2d26d69949ff760b0d, [`cbrain_system_checks.rb:204`](https://github.com/aces/cbrain/blob/201219a63c2a264486c16c2d26d69949ff760b0d/BrainPortal/lib/cbrain_system_checks.rb#L204) ensures that the Portal will have a valid `auth_token` or will show a warning message otherwise.

The portal cannot refuse to start, as it must start even if a cache directory has not been configured (which implies no `auth_token`).
