### ISSUE TITLE
Boutiques task generate crashes if descriptor has an input with no value-key

### ISSUE THREAD

**Issue by glatard** [aces/cbrain#660]

**Comment by prioux** [comment]
Not sure if this is the same as #527 ?

**Comment by glatard** [comment]
no, it's a different one.

**Comment by natacha-beck** [comment]
@glatard the following PR #912 will fix this issue. But if I look to your [Boutiques descriptor](https://github.com/glatard/Shape-Appearance-Model/blob/67aee58e80b5c0d00cf1dc20942a09bfa14ed4cd/boutiques/cbrain-plugins-runpg/cbrain_task_descriptors/runPG.json) that raise this error. I did not understand what the inputs with the id `input_directory` will do, since it will never put anywhere in the command line.

**Comment by prioux** [comment]
@glatard The question we have is: In boutiques, what is the meaning of an input that has no `value-key` ? How does that make sense?

**Comment by glatard** [comment]
The main use-case is when the application requires files (or directories) which do not appear on the command line or in any configuration file. I've seen 2 types of tools requiring that: (1) tools that require an external config file with a hardcoded name (e.g., env.sh or database.db), and (2) tools that will scan for, say, nifti files in all sub-directories to process them. I agree it's not super clean but sometimes it's just how it is.

**Comment by prioux** [comment]
Ah, I see. So bosh, for instance, will check for the presence of the file even if it's not explicitely in the command?

**Comment by prioux** [comment]
Well, with Natacha's patch, CBRAIN handles the input properly (by ignoring it without crashing).

**Comment by glatard** [comment]
if it's a file, the input should still be synchronized to the execution server though.

**Comment by prioux** [comment]
Of course, and I'm pretty sure that's already happening. The code that sync file data is separate from the one that builds the command to run.

**Comment by prioux** [comment]
Fixed by #912
