### ISSUE TITLE
Try to run the testing suite with --order rand option 

### ISSUE THREAD

**Issue by natacha-beck** [aces/cbrain#76]
Since all the testing suite is normally fixed. It will be a good idea to run in a random order: 

```
rspec --order rand spec/
```

multiple times in order to see is some tests break or not.

**Comment by natacha-beck** [comment]
Some test failed with the following seeds:

- 34701
- 48090
- 42668

**Comment by natacha-beck** [comment]
Improve speed performance too!

**Comment by remibernard** [comment]
The failed tests are due to rspec's `File` mocks interfering with Rails' autoloader; some tests require mocking `File.directory?` to always return `true`, which causes the autoloader to incorrectly consider unknown class (and module) names as modules under the currently active module.

See [dependencies:431](https://github.com/rails/rails/blob/3-2-stable/activesupport/lib/active_support/dependencies.rb#L431) and [dependencies:505](https://github.com/rails/rails/blob/3-2-stable/activesupport/lib/active_support/dependencies.rb#L505)
I have no idea how to cleanly fix this. It could potentially happen with any base ruby class mock.

**Comment by natacha-beck** [comment]
New bug with seed: 30805

**Comment by natacha-beck** [comment]
Other one: 9643 and 707

**Comment by remibernard** [comment]
I can only reproduce the bugs of seed 707. 9643 and 30805 work just fine for me. (`Works on my machine!`)

**Comment by remibernard** [comment]
As of f558a185e90cc9fe86308147f0cafa03480398e0, the only reproducible test failures are due to `File` mocks as described above (with `CbrainError` as the loaded class).
