### ISSUE TITLE
NeuroHub Alpha user feedback - technical issue - license and project creation 

### ISSUE THREAD

**Issue by bryancaron** [aces/cbrain#960]
Received via direct email message sent to Diana:

a) Licence: Easy. If it’s ‘mandatory’ to sign it (as the creator of the project) should it pop-up when creating a project … asking you to create a licence and sign it?

**Comment by MontrealSergiy** [comment]
Not sure is it good idea to sign on the same page where it is created would like hear somebody elses opinion . @xlecours I am not sure is it mandatory just decided play save and in same fasion as cbrain does. But perhaps we can allow the maintainer and perhaps former maintainers to access project without signing anything.

**Comment by xlecours** [comment]
I think it could popup as soon as the page reloads. The maintainer who just added the licence would effectively be trying to access a project that he has not sign the licence (the general use case).

**Comment by prioux** [comment]
Wait, I thought I understood this issue but now I'm all confused.

Correct me if I'm wrong, but right now a user can create a project, and at any time that user can add a licence to it. As soon as the licence is added, neurohub will prompt all members of the project to sign the license in order to be able to continue accessing it. That even includes the user who added the license. That all seems straightforward to me.

Is the problem simply that a user is surprised to have to sign their own licence when they add it? If so we can very easily modify the code so that as soon as someone adds a licence, that person automatically has signed it too as a side effect. It's pretty trivial.

Or is the bug about something else?

**Comment by natacha-beck** [comment]
For me it seems to be the issue. 

If it is the case your solution is fine, maybe add a comment on the page where user can add the licence telling they that the licence will be automatically sign it for him.

**Comment by MontrealSergiy** [comment]
"very easily modify the code so that as soon as someone adds a licence, that person automatically has signed it too as a side effect. It's pretty trivial."  I would prefer to releave the current maintainer from signing. Signing automatically does not seems nice to user. I do not like any software sign any sketchy agreements on my behalf .

**Comment by natacha-beck** [comment]
That´s why I ask to inform the user that it will be automatically sign it.

**Comment by MontrealSergiy** [comment]
> 
> 
> I think it could popup as soon as the page reloads. The maintainer who just added the licence would effectively be trying to access a project that he has not sign the licence (the general use case).

that is how it works now. but user is surprised a bit of that

**Comment by prioux** [comment]
Why is this so complicated? If a maintainer adds a license, it seems a no-brainer than they accept it themselves. So we can make it automatic.

On the other hand, right now the fact that they have to sign it after creating it is a bit cumbersome but it has the advantage that the person who added the licence can also review what it will look like to other users.

**Comment by prioux** [comment]
It's not like we expect that there will be people adding a license to a project yet not wanting to abide to their own licence, right?

**Comment by MontrealSergiy** [comment]
No strong opinion here. Yet, some people are just like that,  especially in commercial field. Frequently those want you to not to share their code or data with others, but do not like restrict themselves from distributing that code or data for gain or fun. Even in open source domain some would expect some form of written or oral gratitude from others, may be just a little credit. But not from themselves.

**Comment by MontrealSergiy** [comment]
I would go just for verbiage enhancement for now as suggested, though one day some maintainers would start resenting their own license agreement.

**Comment by Najmahan** [comment]
Is anyone interested in me user-testing something for you? :)

**Comment by bryancaron** [comment]
License is not mandatory. 
Creator should not have to sign licence.  May also apply to editor in terms of having to currently sign the license.

Desired behaviour: person (creator or editor) creating license should not have to sign, but other editor (or user ie. everyone else) should have to sign.

**Comment by bryancaron** [comment]
Estimated 1 - 2 days max
